version: 2

updates:
- package-ecosystem: "uv"
  directory: "/"
  schedule:
    interval: "weekly"
  target-branch: "develop"
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  target-branch: "develop"
  open-pull-requests-limit: 10
  
