services:
  hohumi:
    image: "ghcr.io/being24/hohumi:latest"
    volumes:
      - ./data:/usr/src/hohumi/data
      - ./log:/usr/src/hohumi/log
    env_file:
      - ./.env
    restart: always
